const svg=document.querySelector('#canvas'), ns='http://www.w3.org/2000/svg';
const input=id=>document.querySelector(`#${id}`), layer=name=>document.querySelector(`[data-layer=${name}]`).checked;
const colors=['#1864ab','#e67700']; let mapData,planData,drawTarget=null,firstCorner=null,animationFrame=null;
let regions=[null,null], animation=null;
const strategyNames={auto:'自动比较',contour_outward:'由内向外轮廓搜索',lawn_mower:'往复式覆盖搜索'};
function el(tag,attrs={},cls){const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(cls)n.setAttribute('class',cls);return n}
const points=ring=>ring.map(p=>`${p[0]},${-p[1]}`).join(' ');
function rings(g){if(!g)return[];if(g.type==='Polygon')return g.coordinates.map((r,i)=>({ring:r,hole:i>0}));if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map((r,i)=>({ring:r,hole:i>0})));return[]}
function addGeometry(g,cls,style=''){rings(g).filter(x=>!x.hole).forEach(x=>svg.append(el('polygon',{points:points(x.ring),style},cls)))}
function defaultRegions(){const [a,b,c,d]=mapData.background.bounds,m=(a+c)/2;regions=[rectGeo(a,b,m,d),rectGeo(m,b,c,d)]}
function rectGeo(x1,y1,x2,y2){const a=Math.min(x1,x2),b=Math.min(y1,y2),c=Math.max(x1,x2),d=Math.max(y1,y2);return{type:'Polygon',coordinates:[[[a,b],[c,b],[c,d],[a,d],[a,b]]]}}
function draw(){svg.innerHTML='';if(!mapData)return;const [a,b,c,d]=mapData.background.bounds;if(layer('background'))svg.append(el('image',{href:`${mapData.background.url}?v=3`,x:a,y:-d,width:c-a,height:d-b,preserveAspectRatio:'none'}));
 addGeometry(mapData.search_area,'boundary','fill:none;stroke:#c92a2a;stroke-width:.8px');
 regions.forEach((g,i)=>addGeometry(g,`responsibility responsibility-${i+1}`,`fill:${colors[i]};fill-opacity:.10;stroke:${colors[i]};stroke-width:1px`));
 const drones=planData?.drones??[];
 if(layer('coverage'))drones.forEach((d,i)=>addGeometry(d.summary.visible_detection_area,'valid-coverage',`fill:${colors[i]};fill-opacity:.17;stroke:${colors[i]};stroke-opacity:.28;stroke-width:.18px`));
 if(layer('patches'))drones.forEach((d,i)=>d.summary.patches.forEach(p=>addGeometry(p.geometry,p.covered?'patch':'patch uncovered',`fill:${p.covered?colors[i]:'#d95d5d'};fill-opacity:.13;stroke:#fff;stroke-width:.1px`)));
 if(layer('buildings'))mapData.buildings.forEach(bu=>{const [x1,y1,x2,y2]=bu.bounds,r=el('rect',{x:x1,y:-y2,width:x2-x1,height:y2-y1},'building'),t=el('title');t.textContent=`${bu.id} · 高度 ${bu.height_m.toFixed(1)} 米`;r.append(t);svg.append(r)});
 drones.forEach((d,i)=>{const route=d.summary.flight_waypoints;if(layer('route'))svg.append(el('polyline',{points:route.map(w=>`${w.x},${-w.y}`).join(' '),style:`stroke:${colors[i]}`},'route'));if(layer('waypoints'))route.forEach(w=>svg.append(el('circle',{cx:w.x,cy:-w.y,r:.75,style:`fill:${colors[i]}`},'waypoint')))});
 [0,1].forEach(i=>{const h=[+input(`home${i+1}-x`).value,+input(`home${i+1}-y`).value];if(h.every(Number.isFinite))svg.append(el('circle',{cx:h[0],cy:-h[1],r:2,style:`fill:${colors[i]}`},'home'))});drawAnimation()}
function drawAnimation(){if(!animation)return;animation.forEach((s,i)=>{if(s.travelled.length>1)svg.append(el('polyline',{points:s.travelled.map(points=>`${points[0]},${-points[1]}`).join(' '),style:`stroke:${colors[i]}`},'travelled'));if(s.position)svg.append(el('circle',{cx:s.position[0],cy:-s.position[1],r:1.7,style:`fill:${colors[i]}`},'drone'))})}
function replay(){const drones=planData?.drones;if(!drones)return;cancelAnimationFrame(animationFrame);animation=drones.map(d=>({segment:0,progress:0,last:null,position:[d.summary.flight_waypoints[0].x,d.summary.flight_waypoints[0].y],travelled:[]}));input('replay').disabled=true;
 function step(time){let active=false;animation.forEach((s,i)=>{const route=drones[i].summary.flight_waypoints;if(s.segment>=route.length-1)return;active=true;if(s.last===null)s.last=time;const dt=Math.min(50,time-s.last);s.last=time;const a=route[s.segment],b=route[s.segment+1],dist=Math.hypot(b.x-a.x,b.y-a.y);s.progress+=dist?dt/1000*(10+18*+input('speed').value)/dist:1;const r=Math.min(1,s.progress);s.position=[a.x+(b.x-a.x)*r,a.y+(b.y-a.y)*r];if(r===1){s.travelled.push([b.x,b.y]);s.segment++;s.progress=0}});draw();if(active)animationFrame=requestAnimationFrame(step);else input('replay').disabled=false}animationFrame=requestAnimationFrame(step)}
function mapPoint(event){let p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;p=p.matrixTransform(svg.getScreenCTM().inverse());return[p.x,-p.y]}
document.querySelectorAll('.draw-region').forEach(b=>b.onclick=()=>{drawTarget=+b.dataset.drone;firstCorner=null;input('draw-tip').textContent=`正在绘制无人机 ${drawTarget+1} 责任区：请点击第一个对角`;input('draw-tip').style.display='block'});
svg.onclick=e=>{if(drawTarget===null)return;const p=mapPoint(e);if(!firstCorner){firstCorner=p;input('draw-tip').textContent='请点击另一个对角'}else{regions[drawTarget]=rectGeo(...firstCorner,...p);drawTarget=null;firstCorner=null;input('draw-tip').style.display='none';planData=null;draw()}};
svg.onmousemove=e=>{const p=mapPoint(e);input('coords').textContent=`ENU 东向 ${p[0].toFixed(1)}，北向 ${p[1].toFixed(1)}`};
document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=draw);['home1-x','home1-y','home2-x','home2-y'].forEach(id=>input(id).oninput=draw);input('replay').onclick=replay;
function payload(){return{drones:[0,1].map(i=>({drone_id:`drone_${i+1}`,search_geometry:regions[i],home_x_m:+input(`home${i+1}-x`).value,home_y_m:+input(`home${i+1}-y`).value})),flight_altitude_m:+input('alt').value,horizontal_clearance_m:+input('hc').value,vertical_clearance_m:+input('vc').value,scan_direction_deg:+input('angle').value,scan_pattern:input('pattern').value,video_analysis_rate_hz:+input('frequency').value,control_point_spacing_m:+input('control-spacing').value,coverage_speed_mps:+input('lane-speed').value,connector_speed_mps:+input('connector-speed').value,obstacle_speed_mps:+input('obstacle-speed').value,return_speed_mps:+input('connector-speed').value,camera:{image_width_px:1920,image_height_px:1080,horizontal_fov_deg:+input('hfov').value,vertical_fov_deg:+input('vfov').value,pitch_deg:-90,yaw_mode:'follow_path',forward_overlap:+input('fo').value,side_overlap:+input('so').value,target_width_m:+input('target-width').value,target_length_m:+input('target-length').value,target_height_m:+input('target-height').value,image_boundary_margin_ratio:+input('image-margin').value}}}
input('plan').onclick=async()=>{const button=input('plan');input('error').style.display='none';button.disabled=true;button.textContent='正在同时规划…';try{const r=await fetch('/api/plan-dual',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())}),body=await r.json();if(!r.ok)throw new Error(body.detail||`规划失败（${r.status}）`);planData=body;animation=null;input('summary').innerHTML='<h2>规划结果</h2>'+body.drones.map((d,i)=>{const s=d.summary;return`<p><strong style="color:${colors[i]}">无人机 ${i+1}</strong><br>策略：${strategyNames[s.scan_pattern]??s.scan_pattern}<br>有效覆盖率：${(100*s.coverage_ratio).toFixed(2)}%<br>航程：${s.path_length_m.toFixed(0)} 米<br>检测航线：${s.lane_count} 条<br>飞控途径点：${s.flight_waypoint_count} 个<br>视野计算样本：${s.visibility_sample_count} 个</p>`}).join('');input('exports').innerHTML='<a href="/api/export/mission_manifest.json">双机任务清单（JSON）</a>'+body.drones.map((d,i)=>`<p><strong>无人机 ${i+1}</strong><br><a href="/api/export/${d.drone_id}/flight_plan.json">飞控计划（JSON）</a><br><a href="/api/export/${d.drone_id}/coverage_report.json">覆盖报告（JSON）</a><br><a href="/api/export/${d.drone_id}/visualization.png">规划结果图（PNG）</a></p>`).join('');draw();input('replay').disabled=false}catch(e){input('error').textContent=e.message;input('error').style.display='block'}finally{button.disabled=false;button.textContent='同时规划两架无人机'}};
async function load(){try{const r=await fetch('/api/map');mapData=await r.json();defaultRegions();draw()}catch(e){input('error').textContent='地图加载失败，请确认规划服务正在运行。';input('error').style.display='block'}}load();
