const input=id=>document.getElementById(id),svg=input('canvas'),colors=['#1864ab','#e67700'];
let mapData,regions=[],planData,drawTarget=null,firstCorner=null,animation=null,frame=null;
const layer=name=>document.querySelector(`[data-layer=${name}]`).checked;
function el(tag,attrs={},className=''){const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [key,value]of Object.entries(attrs))node.setAttribute(key,value);if(className)node.setAttribute('class',className);return node}
function rings(g){if(!g||g.type==='GeometryCollection')return[];if(g.type==='Polygon')return g.coordinates.map((ring,index)=>({ring,hole:index>0}));if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map((ring,index)=>({ring,hole:index>0})));return[]}
function points(ring){return ring.map(([x,y])=>`${x},${-y}`).join(' ')}
function addGeometry(g,className,style=''){rings(g).forEach(item=>svg.append(el('polygon',{points:points(item.ring),style},`${className}${item.hole?' hole':''}`)))}
function rect(x1,y1,x2,y2){const a=Math.min(x1,x2),b=Math.min(y1,y2),c=Math.max(x1,x2),d=Math.max(y1,y2);return{type:'Polygon',coordinates:[[[a,b],[c,b],[c,d],[a,d],[a,b]]]}}
function defaults(){const[a,b,c,d]=mapData.background.content_bounds,m=(a+c)/2;regions=[rect(a,b,m,d),rect(m,b,c,d)]}
function viewport(){const[a,b,c,d]=mapData.background.content_bounds,p=18;svg.setAttribute('viewBox',`${a-p} ${-d-p} ${c-a+2*p} ${d-b+2*p}`)}
function segment(a,b,className,style){svg.append(el('line',{x1:a.x,y1:-a.y,x2:b.x,y2:-b.y,style},className))}
function draw(){svg.innerHTML='';if(!mapData)return;const[a,b,c,d]=mapData.background.bounds;if(layer('background'))svg.append(el('image',{href:mapData.background.url,x:a,y:-d,width:c-a,height:d-b,preserveAspectRatio:'none'}));addGeometry(mapData.search_area,'search-boundary');regions.forEach((g,i)=>addGeometry(g,'responsibility',`fill:${colors[i]};fill-opacity:.1;stroke:${colors[i]};stroke-width:1px`));if(layer('buildings'))mapData.buildings.forEach(building=>{const[x1,y1,x2,y2]=building.bounds;svg.append(el('rect',{x:x1,y:-y2,width:x2-x1,height:y2-y1},'building'))});const drones=planData?.drones||[];if(layer('coverage'))drones.forEach((d,i)=>{if(animation)animation[i].coverage.forEach(g=>addGeometry(g,'animated-coverage',`fill:${colors[i]};fill-opacity:.12;stroke:none`));else addGeometry(d.summary.visible_detection_area,'valid-coverage',`fill:${colors[i]};fill-opacity:.14;stroke:${colors[i]};stroke-width:.4px`)});drones.forEach((d,i)=>{const route=d.summary.flight_waypoints||[],byId=Object.fromEntries(route.map(w=>[w.id,w]));(d.summary.route_segments||[]).forEach(s=>{const a=byId[s.start_waypoint_id],b=byId[s.end_waypoint_id];if(!a||!b)return;if(s.kind==='coverage_lane'&&layer('lanes'))segment(a,b,'lane-route',`stroke:${colors[i]}`);if(s.kind!=='coverage_lane'&&layer('transitions'))segment(a,b,'transition-route',`stroke:${i?'#9c4f00':'#7048a8'}`)});if(layer('waypoints'))route.forEach(w=>svg.append(el('circle',{cx:w.x,cy:-w.y,r:.7,style:`fill:${colors[i]}`},'waypoint')))});[0,1].forEach(i=>{const h=[+input(`home${i+1}-x`).value,+input(`home${i+1}-y`).value];svg.append(el('circle',{cx:h[0],cy:-h[1],r:2,style:`fill:${colors[i]}`},'home'))});if(animation)animation.forEach((state,i)=>svg.append(el('circle',{cx:state.position[0],cy:-state.position[1],r:1.8,style:`fill:${colors[i]}`},'drone')))}
function mapPoint(event){let p=svg.createSVGPoint();p.x=event.clientX;p.y=event.clientY;p=p.matrixTransform(svg.getScreenCTM().inverse());return[p.x,-p.y]}
document.querySelectorAll('.draw-region').forEach(button=>button.onclick=()=>{drawTarget=+button.dataset.drone;firstCorner=null;input('draw-tip').textContent=`绘制无人机 ${drawTarget+1}：点击第一个对角`;input('draw-tip').style.display='block'});
svg.onclick=e=>{if(drawTarget===null)return;const p=mapPoint(e);if(!firstCorner){firstCorner=p;input('draw-tip').textContent='点击另一个对角'}else{regions[drawTarget]=rect(...firstCorner,...p);drawTarget=null;firstCorner=null;planData=null;animation=null;input('draw-tip').style.display='none';draw()}};
svg.onmousemove=e=>{const p=mapPoint(e);input('coords').textContent=`ENU 东向 ${p[0].toFixed(1)}，北向 ${p[1].toFixed(1)}`};document.querySelectorAll('[data-layer]').forEach(box=>box.onchange=draw);['home1-x','home1-y','home2-x','home2-y'].forEach(id=>input(id).oninput=draw);
function payload(){const direction=input('direction').value;return{drones:[0,1].map(i=>({drone_id:`drone_${i+1}`,search_geometry:regions[i],home_x_m:+input(`home${i+1}-x`).value,home_y_m:+input(`home${i+1}-y`).value})),flight_altitude_m:+input('alt').value,horizontal_clearance_m:+input('hc').value,vertical_clearance_m:+input('vc').value,scan_direction_deg:direction==='auto'?null:+direction,coverage_generation_method:'global_scanline',route_optimization_method:'auto',video_analysis_rate_hz:1,control_point_spacing_m:+input('control-spacing').value,coverage_speed_mps:+input('lane-speed').value,connector_speed_mps:+input('connector-speed').value,obstacle_speed_mps:+input('obstacle-speed').value,return_speed_mps:+input('connector-speed').value,camera:{image_width_px:1920,image_height_px:1080,horizontal_fov_deg:+input('hfov').value,vertical_fov_deg:+input('vfov').value,pitch_deg:-90,yaw_mode:'follow_path',forward_overlap:+input('fo').value,side_overlap:+input('so').value,target_width_m:2.5,target_length_m:6,target_height_m:2.5,image_boundary_margin_ratio:.05}}}
function replay(){if(!planData)return;cancelAnimationFrame(frame);animation=planData.drones.map(d=>({route:d.summary.flight_waypoints,index:0,fraction:0,position:[d.summary.flight_waypoints[0].x,d.summary.flight_waypoints[0].y],coverage:[],sampleIndex:0,samples:d.summary.visibility_samples||[],last:null}));input('replay').disabled=true;draw();function step(time){let active=false;animation.forEach(state=>{if(state.index>=state.route.length-1)return;active=true;if(state.last===null)state.last=time;const dt=Math.min(50,time-state.last);state.last=time;const a=state.route[state.index],b=state.route[state.index+1],distance=Math.hypot(b.x-a.x,b.y-a.y),speed=(6+6*+input('speed').value);state.fraction+=distance?dt/1000*speed/distance:1;const ratio=Math.min(1,state.fraction),progress=(state.index+ratio)/(state.route.length-1);state.position=[a.x+(b.x-a.x)*ratio,a.y+(b.y-a.y)*ratio];while(state.sampleIndex<state.samples.length&&state.samples[state.sampleIndex].route_progress<=progress){state.coverage.push(state.samples[state.sampleIndex].geometry);state.sampleIndex++}if(ratio===1){state.index++;state.fraction=0}});draw();if(active)frame=requestAnimationFrame(step);else input('replay').disabled=false}frame=requestAnimationFrame(step)}
input('replay').onclick=replay;function message(detail,status){if(typeof detail==='string')return detail;if(Array.isArray(detail))return detail.map(x=>x.msg).join('；');return`规划失败（${status}）`}
input('plan').onclick=async()=>{const button=input('plan');button.disabled=true;button.textContent='正在规划…';input('error').style.display='none';try{const response=await fetch('/api/plan-dual',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())}),body=await response.json();if(!response.ok)throw new Error(message(body.detail,response.status));planData=body;animation=null;input('summary').innerHTML='<h2>规划结果</h2>'+body.drones.map((d,i)=>{const s=d.summary;return`<p style="color:${colors[i]}"><strong>无人机 ${i+1}</strong><br>覆盖率 ${(100*s.coverage_ratio).toFixed(4)}% · 未覆盖 ${s.uncovered_patch_count}<br>${s.lane_count} 条 lane · ${s.path_length_m.toFixed(1)} 米 · ${s.flight_waypoint_count} 航点</p>`}).join('');input('exports').innerHTML='<a href="/api/export/mission_manifest.json">双机任务清单</a>'+body.drones.map(d=>`<a href="/api/export/${d.drone_id}/flight_plan.json">${d.drone_id} 飞控计划</a><a href="/api/export/${d.drone_id}/coverage_report.json">${d.drone_id} 覆盖报告</a>`).join('');input('replay').disabled=false;draw()}catch(error){input('error').textContent=error.message;input('error').style.display='block'}finally{button.disabled=false;button.textContent='生成两架无人机航线'}};
async function load(){try{const response=await fetch('/api/map');mapData=await response.json();viewport();defaults();draw()}catch(error){input('error').textContent='地图加载失败';input('error').style.display='block'}}load();
